### PR TITLE
chore(package): remove engines field

### PR DESCRIPTION
**Pull request by Fdawgs**
Missed this in https://github.com/pinojs/real-require/pull/45

### CODE REVIEW

**Comment by mcollina** [comment]
This conflicts

**Comment by Fdawgs** [comment]
> This conflicts

sorted

**Comment by Fdawgs** [comment]
Mind reviewing/merging this and https://github.com/pinojs/pino-filter/pull/48 please @mcollina?

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
